# Generated by Django 4.2.1 on 2023-07-23 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plays',
            name='week',
        ),
        migrations.RemoveField(
            model_name='plays',
            name='year',
        ),
    ]
